### ISSUE TITLE
Formatting a config file - range option

### ISSUE THREAD

**Issue by KevDonn** [cgab-ncc/FIREVAT#11]
Hi All, 

We're keen to try FIREVAT for filtering our variant calls, and I'm currently attempting to create a config file to process vardict calls. However, I'm not entirely clear on how to create rules for this file, specifically on how 'range' is interpreted.

The definition from the docs is "filtering range of value ( [min, max])", but I don't understand exactly what is meant by this, or how it will effect the output. 

For example, in the default config file for Mutect2 the 'TumorADAlt' parameter has the following default and range values:

"name":TumorADAlt 
"default": 3 
"range": [3, 10]  

The Strelka config has the following:

"name": "TumorAltAD"
"default": 10
"range": [0, 10]

Would you be able to explain what these values mean in practice, and why they differ between callers? This would be a great help in creating a new config for vardict.

Many thanks,
Kevin

**Comment by khb7840** [comment]
Dear Kevin,
Firevat limit its search space within the range.
If you don’t give one, it will use the minimum and maximum value as the range (which can be very big as some range of parameters like read depth is quite huge to search one by one)
The difference of ranges between callers are due to the differences from various output.

Thank you for using FIREVAT!
Sincerely, 
Hyunbin Kim

**Comment by KevDonn** [comment]
Thanks for your swift response - it's much appreciated!

I think that I understand. I can see that the parameters used in the defualt config file vary among callers. When trying to create a new config file from scratch, what should my considerations be? As an example, for Vardict I've included AD for normal and tumour using the same ranges as used in the Mutect2 config. 

* Am I liable to harm the analysis if I include additional fields that don't explain much variation between artefacts and non-artefacts, or will I simply increase the processing time?
* With regards to min/max range values, if I understand correctly, I should choose the range within which I expect the optimal cut-off value to lie?

Thanks again,
Kevin

**Comment by khb7840** [comment]
1. FIREVAT will find the cutoffs from your additional fields anyway (It will be optimized but will take more time because additional fields enlarge the searching space)
2. If you give the optimal range, it will help FIREVAT to find the optimal cutoff faster.

**Comment by KevDonn** [comment]
Ah, I understand now. Thanks again for your help, it's been very useful.
