### ISSUE TITLE
Error in read.vcf() 

### ISSUE THREAD

**Issue by master-noddy** [cgab-ncc/FIREVAT#7]
I have been getting the same error while loading the vcf file, please someone help me to correct me if I am doing anything wrong. Below I have pasted the whole terminal commands with the error in the last line.

output.dir <- "/data/sata_data/home/dl7/FIREVAT_report"
sample.vcf.file <- system.file("extdata", "/data/sata_data/home/dl7/FIREVAT_report/Sample_114T_Sample_114N_matched_m2_snvs_indels_filter.vcf", package = "FIREVAT")
config.file <-system.file("config","/data/sata_data/home/dl7/FIREVAT_report/114T_mergeFiltered.json", package = "
results <- RunFIREVAT(
    vcf.file = sample.vcf.file,
    vcf.file.genome = 'hg19',
    config.file = config.file,
    df.ref.mut.sigs = GetPCAWGMutSigs(),
    target.mut.sigs = GetPCAWGMutSigsNames(),
    df.ref.mut.sigs.groups.colors = GetPCAWGMutSigsEtiologiesColors(),
    sequencing.artifact.mut.sigs = PCAWG.All.Sequencing.Artifact.Signatures,
    output.dir = output.dir,
    objective.fn = Default.Obj.Fn,
    num.cores = 2,
    ga.pop.size = 100,
    ga.max.iter = 5,
    ga.run = 5,
    ga.pmutation = 0.1,
    perform.strand.bias.analysis = TRUE,
    ref.forward.strand.var = "TumorDPRefForward",
    ref.reverse.strand.var = "TumorDPRefReverse",
    alt.forward.strand.var = "TumorDPAltForward",
    alt.reverse.strand.var = "TumorDPAltReverse",
    annotate = FALSE)+ + + + + + + + + + + + + + + + + + + + 
[1] "INFO [2020-05-30 16:46:43] Started running FIREVAT."
[1] "INFO [2020-05-30 16:46:43] Step 01. Initialize FIREVAT input parameters."
[1] "INFO [2020-05-30 16:46:43] Step 01-1. Output directory /data/sata_data/home/dl7/FIREVAT_report already exists."
[1] "INFO [2020-05-30 16:46:43] Step 01-2. Read VCF file [firevat_vcf::ReadVCF]."
Error in read.vcf(x = vcf.file, split.info = split.info, verbose = FALSE) :

**Comment by master-noddy** [comment]
I am getting the same error while loading the files given with the tool. 
Please someone address my issue

**Comment by master-noddy** [comment]
I am getting the same error while loading the files given with the tool.
Please someone address my issue

**Comment by andyjslee** [comment]
Hello, 

I have just tested the example code using the latest release (v0.6.0) and FIREVAT runs without any bugs. Your problem appears to be specific to your VCF or custom configuration file. If it's okay with you, could you please send the files to jinseok.lee@ncc.re.kr? I'll take a look at them and assist you from there.

Thanks,
Andy

**Comment by V-Catherine** [comment]
Hello,
Could you provide an example of vcf that should work because I have the same issue and I've tested with different vcf files with no success. The variable sample.vcf.file stays empty. I have no issue with the config.file.
Thanks in advance for your help
Catherine

**Comment by khb7840** [comment]
I'm not sure what's the reason of the error but you just can use the path of vcf file to vcf.file instead of using system.file().
We use system.file() for the vcf files included in the package.
