### ISSUE TITLE
reshape2::melt(df.temp) error

### ISSUE THREAD

**Issue by master-noddy** [cgab-ncc/FIREVAT#8]
I am loading the files provided with the tool "DCC_PCAWG_Cell_Lines_HCC1143.vcf" and "PCAWG_DKFZ_Cell_Line_Filtering_Params.json" and getting this error

[1] "INFO [2020-06-08 14:29:01] Step 05. Generate FIREVAT report"
[1] "INFO [2020-06-08 14:29:01] * Started generating FIREVAT report"
[1] "INFO [2020-06-08 14:29:01] ** Started plotting optimization iterations"
Error in grDevices::png(..., res = dpi, units = "in") : 
  X11 is not available
In addition: Warning message:
In melt(df.temp, id.vars = x.axis.var) :
  The melt generic in data.table has been passed a data.frame and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(df.temp). In the next version, this warning will become an error.

**Comment by khb7840** [comment]
Hi @master-noddy!
I think this error message is related to X11 connection which is necessary to draw figures and save them into png format. Please check closed issue #3. 
We'll also check the warning message on reshape2::melt and update if needed.
Thank you for comment!
